### PR TITLE
Added block_ruler, for horizontal rules.

### PR DESCRIPTION
**Pull request by samwilson**
As per: http://asciidoctor.org/docs/user-manual/#horizontal-rules

### CODE REVIEW

**Comment by samwilson** [comment]
Oh yes, and Asciidoc calles these [rulers](http://asciidoc.org/userguide.html#_rulers).

**Comment by samwilson** [comment]
(bump)

**Comment by sethwoodworth** [comment]
Agreed!

**Comment by samwilson** [comment]
Thanks! :)

**Pull request merged**
